# Generated by Django 4.2 on 2026-04-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_car_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
