# Generated by Django 6.0.4 on 2026-05-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
