# Generated by Django 6.0.4 on 2026-05-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_car_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
    ]
